on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout del cdigo
        uses: actions/checkout@v4
      - name: Configuracion de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar pruebas
        run: npm test
